import { BotProfile, BotCategory } from '../types';

export const CHESS_BOTS: BotProfile[] = [
  // -------------------------------------------------------------
  // BEGINNER TIER (250 - 850)
  // -------------------------------------------------------------
  {
    id: 'bot_martin',
    name: 'Martin',
    rating: 250,
    title: 'Beginner',
    category: 'beginner',
    avatar: 'MA',
    avatarBg: 'bg-amber-100 border-amber-300 text-amber-900',
    avatarTextColor: 'text-amber-800',
    bio: 'Martin is learning chess alongside his kids. He often leaves pieces unprotected and misses basic captures.',
    playstyle: 'Casual & Erratic',
    favoriteOpenings: ["King's Pawn", "Queen's Pawn"],
    depth: 1,
    blunderRate: 0.55,
    inaccuracyRate: 0.35,
    aggressiveness: 0.3,
    positionalWeight: 0.1,
    tacticalVision: 0.15,
    useOpeningBook: false,
    tagline: 'Just learning the basic rules!'
  },
  {
    id: 'bot_elani',
    name: 'Elani',
    rating: 400,
    title: 'Beginner',
    category: 'beginner',
    avatar: 'EL',
    avatarBg: 'bg-emerald-100 border-emerald-300 text-emerald-900',
    avatarTextColor: 'text-emerald-800',
    bio: 'Elani knows how all the pieces move and loves capturing pawns, but struggles with checks and knight forks.',
    playstyle: 'Eager Captures',
    favoriteOpenings: ['Italian Game', 'French Defense'],
    depth: 1,
    blunderRate: 0.40,
    inaccuracyRate: 0.30,
    aggressiveness: 0.45,
    positionalWeight: 0.2,
    tacticalVision: 0.25,
    useOpeningBook: true,
    tagline: 'Loves capturing pieces whenever available.'
  },
  {
    id: 'bot_aron',
    name: 'Aron',
    rating: 700,
    title: 'Novice',
    category: 'beginner',
    avatar: 'AR',
    avatarBg: 'bg-blue-100 border-blue-300 text-blue-900',
    avatarTextColor: 'text-blue-800',
    bio: 'Aron develops his pieces in the opening and tries to castle, but sometimes overlooks back-rank tactics and pins.',
    playstyle: 'Developing Novice',
    favoriteOpenings: ['Scotch Game', 'Scandinavian Defense'],
    depth: 2,
    blunderRate: 0.25,
    inaccuracyRate: 0.25,
    aggressiveness: 0.5,
    positionalWeight: 0.35,
    tacticalVision: 0.4,
    useOpeningBook: true,
    tagline: 'Developing fundamentals and piece safety.'
  },
  {
    id: 'bot_mina',
    name: 'Mina',
    rating: 850,
    title: 'Club Junior',
    category: 'beginner',
    avatar: 'MI',
    avatarBg: 'bg-violet-100 border-violet-300 text-violet-900',
    avatarTextColor: 'text-violet-800',
    bio: 'Mina is a sharp young junior player who knows opening principles, spots 1-move tactics, but can be lured into traps.',
    playstyle: 'Sharp & Enthusiastic',
    favoriteOpenings: ['Ruy Lopez', 'Caro-Kann Defense'],
    depth: 2,
    blunderRate: 0.18,
    inaccuracyRate: 0.20,
    aggressiveness: 0.6,
    positionalWeight: 0.45,
    tacticalVision: 0.55,
    useOpeningBook: true,
    tagline: 'Spots 1-move forks and basic pins.'
  },

  // -------------------------------------------------------------
  // INTERMEDIATE TIER (1000 - 1500)
  // -------------------------------------------------------------
  {
    id: 'bot_sven',
    name: 'Sven',
    rating: 1100,
    title: 'Intermediate',
    category: 'intermediate',
    avatar: 'SV',
    avatarBg: 'bg-orange-100 border-orange-300 text-orange-900',
    avatarTextColor: 'text-orange-800',
    bio: 'Sven plays aggressive Scandinavian and King’s Gambit lines. He loves launching king attacks even if they are risky.',
    playstyle: 'Aggressive Attacker',
    favoriteOpenings: ["King's Gambit", 'Sicilian Dragon'],
    depth: 3,
    blunderRate: 0.10,
    inaccuracyRate: 0.18,
    aggressiveness: 0.85,
    positionalWeight: 0.5,
    tacticalVision: 0.65,
    useOpeningBook: true,
    tagline: 'Loves open lines and attacking your king!'
  },
  {
    id: 'bot_nelson',
    name: 'Nelson',
    rating: 1300,
    title: 'Queen Attacker',
    category: 'intermediate',
    avatar: 'NE',
    avatarBg: 'bg-rose-100 border-rose-300 text-rose-900',
    avatarTextColor: 'text-rose-800',
    bio: 'Famous for bringing his Queen out early (Wayward Queen attack). Punishes opponents who panic, but overextends.',
    playstyle: 'Early Queen Pressure',
    favoriteOpenings: ['Wayward Queen Attack', 'Sicilian Defense'],
    depth: 3,
    blunderRate: 0.07,
    inaccuracyRate: 0.15,
    aggressiveness: 0.9,
    positionalWeight: 0.55,
    tacticalVision: 0.7,
    useOpeningBook: true,
    tagline: 'Look out for early queen tricks and forks!'
  },
  {
    id: 'bot_antonio',
    name: 'Antonio',
    rating: 1500,
    title: 'Club Player',
    category: 'intermediate',
    avatar: 'AN',
    avatarBg: 'bg-teal-100 border-teal-300 text-teal-900',
    avatarTextColor: 'text-teal-800',
    bio: 'Antonio is a seasoned club player. He maintains solid center control, protects his king, and rarely blunders pieces.',
    playstyle: 'Solid Classical',
    favoriteOpenings: ["Queen's Gambit", 'Italian Game: Giuoco Piano'],
    depth: 3,
    blunderRate: 0.04,
    inaccuracyRate: 0.12,
    aggressiveness: 0.55,
    positionalWeight: 0.7,
    tacticalVision: 0.75,
    useOpeningBook: true,
    tagline: 'Disciplined club player with solid fundamentals.'
  },

  // -------------------------------------------------------------
  // ADVANCED TIER (1600 - 1900)
  // -------------------------------------------------------------
  {
    id: 'bot_isabel',
    name: 'Isabel',
    rating: 1600,
    title: 'Class A',
    category: 'advanced',
    avatar: 'IS',
    avatarBg: 'bg-indigo-100 border-indigo-300 text-indigo-900',
    avatarTextColor: 'text-indigo-800',
    bio: 'Isabel plays deep positional chess. She looks for outposts, open files, and trades into winning endgames.',
    playstyle: 'Positional & Prophylactic',
    favoriteOpenings: ['London System', 'French Defense: Winawer'],
    depth: 4,
    blunderRate: 0.02,
    inaccuracyRate: 0.08,
    aggressiveness: 0.45,
    positionalWeight: 0.85,
    tacticalVision: 0.82,
    useOpeningBook: true,
    tagline: 'Quiet positional pressure and endgame grinding.'
  },
  {
    id: 'bot_wally',
    name: 'Wally',
    rating: 1800,
    title: 'Expert',
    category: 'advanced',
    avatar: 'WA',
    avatarBg: 'bg-amber-100 border-amber-400 text-amber-950',
    avatarTextColor: 'text-amber-900',
    bio: 'Wally calculates 3-4 moves ahead with high precision. If you leave a pawn weak or overextend, he will exploit it.',
    playstyle: 'Tactical Precision',
    favoriteOpenings: ['English Opening', 'Sicilian Najdorf'],
    depth: 4,
    blunderRate: 0.01,
    inaccuracyRate: 0.05,
    aggressiveness: 0.65,
    positionalWeight: 0.88,
    tacticalVision: 0.90,
    useOpeningBook: true,
    tagline: 'Sharp calculations and punishing tactics.'
  },
  {
    id: 'bot_fatima',
    name: 'Fatima',
    rating: 1900,
    title: 'Candidate Master',
    category: 'advanced',
    avatar: 'FA',
    avatarBg: 'bg-purple-100 border-purple-300 text-purple-900',
    avatarTextColor: 'text-purple-800',
    bio: 'Fatima combines dynamic tactical combinations with deep opening preparation. Very tough to defend against.',
    playstyle: 'Dynamic & Concrete',
    favoriteOpenings: ["King's Indian Defense", 'Ruy Lopez: Marshall Attack'],
    depth: 4,
    blunderRate: 0.005,
    inaccuracyRate: 0.04,
    aggressiveness: 0.75,
    positionalWeight: 0.90,
    tacticalVision: 0.93,
    useOpeningBook: true,
    tagline: 'Master-level preparation and tactical alertness.'
  },

  // -------------------------------------------------------------
  // MASTER & GRANDMASTER TIER (2000 - 3000)
  // -------------------------------------------------------------
  {
    id: 'bot_li',
    name: 'Master Li',
    rating: 2000,
    title: 'FIDE Master (FM)',
    category: 'master',
    avatar: 'LI',
    avatarBg: 'bg-cyan-100 border-cyan-300 text-cyan-900',
    avatarTextColor: 'text-cyan-800',
    bio: 'FM Li possesses a flawless grasp of pawn structures, space advantage, and piece coordination.',
    playstyle: 'Master Prophylaxis',
    favoriteOpenings: ['Catalan Opening', 'Nimzo-Indian Defense'],
    depth: 5,
    blunderRate: 0.002,
    inaccuracyRate: 0.02,
    aggressiveness: 0.60,
    positionalWeight: 0.95,
    tacticalVision: 0.96,
    useOpeningBook: true,
    tagline: 'FIDE Master standard positional mastery.'
  },
  {
    id: 'bot_elena',
    name: 'Elena',
    rating: 2200,
    title: 'International Master (IM)',
    category: 'master',
    avatar: 'EL',
    avatarBg: 'bg-yellow-100 border-yellow-300 text-yellow-950',
    avatarTextColor: 'text-yellow-900',
    bio: 'IM Elena is relentless. She creates multiple simultaneous threats and outplays opponents in complex endgames.',
    playstyle: 'Relentless IM Squeeze',
    favoriteOpenings: ['Grünfeld Defense', 'Ruy Lopez: Closed'],
    depth: 5,
    blunderRate: 0.001,
    inaccuracyRate: 0.015,
    aggressiveness: 0.7,
    positionalWeight: 0.98,
    tacticalVision: 0.98,
    useOpeningBook: true,
    tagline: 'International Master precision and endgame strength.'
  },
  {
    id: 'bot_magnus',
    name: 'Magnus',
    rating: 2850,
    title: 'Grandmaster (GM)',
    category: 'grandmaster',
    avatar: 'MG',
    avatarBg: 'bg-slate-900 border-slate-700 text-amber-400',
    avatarTextColor: 'text-amber-400',
    bio: 'Plays with world-champion caliber precision. Squeezes micro-advantages out of seemingly equal positions with zero mercy.',
    playstyle: 'World Champion Universal',
    favoriteOpenings: ['Spanish Opening', 'Sicilian Sveshnikov', "Queen's Gambit Declined"],
    depth: 6,
    blunderRate: 0.0,
    inaccuracyRate: 0.005,
    aggressiveness: 0.65,
    positionalWeight: 1.0,
    tacticalVision: 1.0,
    useOpeningBook: true,
    tagline: 'Peak Grandmaster strength. Grinds down any mistake.'
  },
  {
    id: 'bot_stockfish',
    name: 'Stockfish Master',
    rating: 3000,
    title: 'Super Engine',
    category: 'grandmaster',
    avatar: 'SF',
    avatarBg: 'bg-emerald-950 border-emerald-600 text-emerald-400',
    avatarTextColor: 'text-emerald-400',
    bio: 'Deep alpha-beta search with quiescence tactical resolution and optimal piece-square heuristic evaluation.',
    playstyle: 'Pure Tactical Supercomputer',
    favoriteOpenings: ['All Main Lines'],
    depth: 6,
    blunderRate: 0.0,
    inaccuracyRate: 0.0,
    aggressiveness: 0.8,
    positionalWeight: 1.0,
    tacticalVision: 1.0,
    useOpeningBook: true,
    tagline: 'Maximum strength depth evaluation engine.'
  }
];

export const DEFAULT_BOT: BotProfile = CHESS_BOTS[6]; // Antonio (1500 Club Player)

export function getBotById(id: string): BotProfile {
  const found = CHESS_BOTS.find(b => b.id === id);
  return found || DEFAULT_BOT;
}

export function getBotsByCategory(category: BotCategory): BotProfile[] {
  return CHESS_BOTS.filter(b => b.category === category);
}
